language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: TOKEN="3"
        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
          env: TOKEN=""
        - os: linux
          dist: precise
          sudo: required
          python: 3.5
          env: TOKEN="3"
        - os: linux
          dist: precise
          sudo: required
          python: 2.7
          env: TOKEN=""

install:
    - sudo apt-get update
    - sudo apt-get install cython graphviz python${TOKEN}-dev
    - sudo apt-get -y install xvfb pulseaudio xclip libmtdev1
    - pip${TOKEN} install cython
    - pip${TOKEN} install coveralls codecov
    - pip${TOKEN} install git+https://github.com/dvolgyes/perceptionmd

before_script:
    - export DISPLAY=:99.0;
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x24 -ac +extension GLX;
    - export PYTHONPATH=$PYTHONPATH:$(pwd);

script:
  - make test

after_success:
  - coveralls
  - codecov
