matrix:
  fast_finish: true
  include:
    - language: python
      python: 2.7
      os: linux
      dist: trusty


install:
    - sudo apt-get update
    - sudo apt-get install python-kivy cython graphviz python-dev
    - sudo apt-get -y install xvfb pulseaudio xclip libmtdev1
    - pip install cython
#    - pip install -r requirements.txt;
    - pip install git+https://github.com/dvolgyes/perception-md

before_script:
    - export DISPLAY=:99.0;
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x24 -ac +extension GLX;
    - export PYTHONPATH=$PYTHONPATH:$(pwd);

script:
  - make test
