language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
          env: PYVERSION=""
        - os: linux
          dist: precise
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: precise
          sudo: required
          python: 2.7
          env: PYVERSION=""

install:
    - sudo apt-get update
    - sudo apt-get install cython graphviz python${PYVERSION}-dev xdotool
    - sudo apt-get -y install xvfb pulseaudio xclip libmtdev1
    - pip${PYVERSION} install --upgrade pip setuptools wheel
    - pip${PYVERSION} install cython
    - pip${PYVERSION} install coveralls codecov
    - pip${PYVERSION} install --only-binary=numpy,scipy scipy
    - pip${PYVERSION} install git+https://github.com/dvolgyes/perceptionmd

before_script:
    - export DISPLAY=:99.0;
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x24 -ac +extension GLX;
    - export PYTHONPATH=$PYTHONPATH:$(pwd);

script:
  - |
    bash input.sh &
    SERVER_PID=$!
  - make test
  - kill -9 $SERVER_PID

after_success:
  - coveralls
