language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
          env: PYVERSION=""
        - os: linux
          dist: precise
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: precise
          sudo: required
          python: 2.7
          env: PYVERSION=""
env:
  global:
   - secure: "LTt3sFx8yq0yAZ2NRgm+HHrI0tpiNJz8PEFZdrUGZmZME2Sz0rdDCi/m0AJHM7Li8Q5zEaR+qirmUJudgW5/1dIclXFfAZV6DNZriSITIOba0s4OFCG/dY0eOFt32xURigR1pAzBBVOdxkCv60wO+WeGZejDdv+oQROrWKiZLx9mMtBPWZAlYvhpxszpJklu0VFQePnFxhP4//BE70+FEyr6CC6/GY0g7Zkq3idCgfUktj1duMeS8Ak3GKDfjifQ5sgQIf3mFynS/wtH9BKa/XvZL5GvX2sXgzVFpRaZE/QcvQNv+XrEH4CLtePyvvjVLzjrHDQE6arn2jMJgLo7lCh8rRwVio0+51QfJm2HuMRQNlHvnE4EoTggc2GpCteKa1tNYSRMpK381zqkbBvhcO7hZ3uM6nWmcm6cf9KrpQ1A3Vd6siI//1V9d9uquiNhY/IftR43KZVwG2+zgbOYTZj+0oPeNm0L6Tr9mi+2yYeFXr3CkkX70D+0kqUDj8tkzOIWqraZS3Dl8KC2EZh1Xiz7BMIhGHSmBBTdb7UnAA8FksiaryG/IvmL+SFelHndOBJeaZjESdu1PMp9UWkB+31++Quv69xSEUOYWyB7fCtGkk4Yj/vncv9/lEI7NpSyDC/6da0dh1yOA9n7tndHyVeoJBJr/lbZ8t8nT0XsYsY="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "dvolgyes/perceptionmd"
      description: "PerceptionMD: perceptual image quality experiments in radiography"
    notification_email: david.volgyes@ieee.org
    build_command_prepend: ""
    build_command:   ""
    branch_pattern: coverity_scan

install:
    - sudo apt-get update
    - sudo apt-get install cython graphviz python${PYVERSION}-dev xdotool
    - sudo apt-get -y install xvfb pulseaudio xclip libmtdev1
    - pip${PYVERSION} install --upgrade pip setuptools wheel
    - pip${PYVERSION} install cython
    - pip${PYVERSION} install coveralls codecov pyflakes
    - pip${PYVERSION} install --only-binary=numpy,scipy scipy
    - pip${PYVERSION} install git+https://github.com/dvolgyes/perceptionmd

before_script:
    - export DISPLAY=:99.0;
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x24 -ac +extension GLX;
    - export PYTHONPATH=$PYTHONPATH:$(pwd);

script:
  - make analyze
  - |
    bash input.sh &
    SERVER_PID=$!
  - make test
  - kill -9 $SERVER_PID

after_success:
  - coveralls
